//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Settings/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""PlayerFarm"",
            ""id"": ""fc760a9f-3396-4bee-ba80-74243840651c"",
            ""actions"": [
                {
                    ""name"": ""DragContact"",
                    ""type"": ""Button"",
                    ""id"": ""554d1912-4cdb-424f-9a1c-431d7b362466"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DragPosition"",
                    ""type"": ""Value"",
                    ""id"": ""f9c557a2-b91b-415d-b4b1-1e13672aba70"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PinchContact"",
                    ""type"": ""Button"",
                    ""id"": ""e5f0da99-c975-46f7-a1cd-c2f438d517a3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PinchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""9064ec9d-1d3e-462a-bc97-3d0a15905ae9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f9b02116-ccf8-4e8f-9b7e-c6ba51533c41"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9174b93-ad5a-4c32-9561-1998aac647dd"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""839134b8-0709-42ed-8ea0-42e8b5b5711e"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PinchContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be2fe76b-6da4-4ed8-a978-5542a8f0af02"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PinchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerFarm
        m_PlayerFarm = asset.FindActionMap("PlayerFarm", throwIfNotFound: true);
        m_PlayerFarm_DragContact = m_PlayerFarm.FindAction("DragContact", throwIfNotFound: true);
        m_PlayerFarm_DragPosition = m_PlayerFarm.FindAction("DragPosition", throwIfNotFound: true);
        m_PlayerFarm_PinchContact = m_PlayerFarm.FindAction("PinchContact", throwIfNotFound: true);
        m_PlayerFarm_PinchPosition = m_PlayerFarm.FindAction("PinchPosition", throwIfNotFound: true);
    }

    ~@InputControls()
    {
        UnityEngine.Debug.Assert(!m_PlayerFarm.enabled, "This will cause a leak and performance issues, InputControls.PlayerFarm.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerFarm
    private readonly InputActionMap m_PlayerFarm;
    private List<IPlayerFarmActions> m_PlayerFarmActionsCallbackInterfaces = new List<IPlayerFarmActions>();
    private readonly InputAction m_PlayerFarm_DragContact;
    private readonly InputAction m_PlayerFarm_DragPosition;
    private readonly InputAction m_PlayerFarm_PinchContact;
    private readonly InputAction m_PlayerFarm_PinchPosition;
    public struct PlayerFarmActions
    {
        private @InputControls m_Wrapper;
        public PlayerFarmActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @DragContact => m_Wrapper.m_PlayerFarm_DragContact;
        public InputAction @DragPosition => m_Wrapper.m_PlayerFarm_DragPosition;
        public InputAction @PinchContact => m_Wrapper.m_PlayerFarm_PinchContact;
        public InputAction @PinchPosition => m_Wrapper.m_PlayerFarm_PinchPosition;
        public InputActionMap Get() { return m_Wrapper.m_PlayerFarm; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerFarmActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerFarmActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerFarmActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerFarmActionsCallbackInterfaces.Add(instance);
            @DragContact.started += instance.OnDragContact;
            @DragContact.performed += instance.OnDragContact;
            @DragContact.canceled += instance.OnDragContact;
            @DragPosition.started += instance.OnDragPosition;
            @DragPosition.performed += instance.OnDragPosition;
            @DragPosition.canceled += instance.OnDragPosition;
            @PinchContact.started += instance.OnPinchContact;
            @PinchContact.performed += instance.OnPinchContact;
            @PinchContact.canceled += instance.OnPinchContact;
            @PinchPosition.started += instance.OnPinchPosition;
            @PinchPosition.performed += instance.OnPinchPosition;
            @PinchPosition.canceled += instance.OnPinchPosition;
        }

        private void UnregisterCallbacks(IPlayerFarmActions instance)
        {
            @DragContact.started -= instance.OnDragContact;
            @DragContact.performed -= instance.OnDragContact;
            @DragContact.canceled -= instance.OnDragContact;
            @DragPosition.started -= instance.OnDragPosition;
            @DragPosition.performed -= instance.OnDragPosition;
            @DragPosition.canceled -= instance.OnDragPosition;
            @PinchContact.started -= instance.OnPinchContact;
            @PinchContact.performed -= instance.OnPinchContact;
            @PinchContact.canceled -= instance.OnPinchContact;
            @PinchPosition.started -= instance.OnPinchPosition;
            @PinchPosition.performed -= instance.OnPinchPosition;
            @PinchPosition.canceled -= instance.OnPinchPosition;
        }

        public void RemoveCallbacks(IPlayerFarmActions instance)
        {
            if (m_Wrapper.m_PlayerFarmActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerFarmActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerFarmActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerFarmActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerFarmActions @PlayerFarm => new PlayerFarmActions(this);
    public interface IPlayerFarmActions
    {
        void OnDragContact(InputAction.CallbackContext context);
        void OnDragPosition(InputAction.CallbackContext context);
        void OnPinchContact(InputAction.CallbackContext context);
        void OnPinchPosition(InputAction.CallbackContext context);
    }
}
